baseURL = 'https://puntowebferrara.com/'
languageCode = 'it'
title = 'Punto Web Ferrara'
enableRobotsTXT = false

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

# Priority personalizzate per pagina nel front matter

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menus.main]]
    name = 'Servizi'
    url = '/servizi/'
    weight = 2
  [[menus.main]]
    name = 'Allevamenti'
    url = '/siti-web-allevamenti/'
    weight = 3
    identifier = 'allevamenti'
  [[menus.main]]
    name = 'Cani'
    url = '/siti-web-allevamenti-cani/'
    weight = 1
    parent = 'allevamenti'
  [[menus.main]]
    name = 'Gatti'
    url = '/siti-web-allevamenti-gatti/'
    weight = 2
    parent = 'allevamenti'
  [[menus.main]]
    name = 'Cavalli'
    url = '/siti-web-allevamenti-cavalli/'
    weight = 3
    parent = 'allevamenti'
  [[menus.main]]
    name = 'Chi Sono'
    url = '/chi-siamo/'
    weight = 4
  [[menus.main]]
    name = 'Portfolio'
    url = '/portfolio/'
    weight = 5
  [[menus.main]]
    name = 'Blog'
    url = '/blog/'
    weight = 6
  [[menus.main]]
    name = 'Contatti'
    url = '/contatti/'
    weight = 7
  [[menus.main]]
    name = 'Preventivo'
    url = '/preventivo/'
    weight = 8

[params]
  description = "Realizzo siti web professionali a Ferrara. Specializzato in siti statici, veloci e sicuri. Preventivo gratuito."
  telefono = "392 463 5584"
  email = "zonerosse@gmail.com"
  indirizzo = "Ostellato (FE)"

[taxonomies]
  # Disabilitate per evitare pagine extra
