baseURL = 'https://puntowebferrara.it/'
languageCode = 'it'
title = 'Punto Web Ferrara'

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menus.main]]
    name = 'Servizi'
    url = '/servizi/'
    weight = 2
  [[menus.main]]
    name = 'Chi Siamo'
    url = '/chi-siamo/'
    weight = 3
  [[menus.main]]
    name = 'Portfolio'
    url = '/portfolio/'
    weight = 4
  [[menus.main]]
    name = 'Contatti'
    url = '/contatti/'
    weight = 5

[params]
  telefono = "333 0000000"
  email = "info@puntowebferrara.it"
  indirizzo = "Ferrara (FE)"
  piva = "00000000000"
