baseURL = 'https://puntowebferrara.com/'
languageCode = 'it'
title = 'Punto Web Ferrara'
enableRobotsTXT = true

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menus.main]]
    name = 'Servizi'
    url = '/servizi/'
    weight = 2
  [[menus.main]]
    name = 'Chi Siamo'
    url = '/chi-siamo/'
    weight = 3
  [[menus.main]]
    name = 'Portfolio'
    url = '/portfolio/'
    weight = 4
  [[menus.main]]
    name = 'Contatti'
    url = '/contatti/'
    weight = 5

[params]
  description = "Realizziamo siti web professionali a Ferrara. Web agency specializzata in SEO e posizionamento Google. Preventivo gratuito."
  telefono = "392 463 5584"
  email = "zonerosse@gmail.com"
  indirizzo = "Ferrara (FE)"
