baseURL = 'https://puntowebferrara.com/'
languageCode = 'it'
title = 'Punto Web Ferrara'
enableRobotsTXT = true

# Sitemap
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menus.main]]
    name = 'Servizi'
    url = '/servizi/'
    weight = 2
  [[menus.main]]
    name = 'Chi Siamo'
    url = '/chi-siamo/'
    weight = 3
  [[menus.main]]
    name = 'Portfolio'
    url = '/portfolio/'
    weight = 4
  [[menus.main]]
    name = 'Contatti'
    url = '/contatti/'
    weight = 5

[params]
  description = "Punto Web Ferrara: realizziamo siti web professionali, SEO e web marketing a Ferrara. Preventivo gratuito."
  telefono = "333 0000000"
  email = "info@puntowebferrara.it"
  indirizzo = "Ferrara (FE)"
  piva = "00000000000"
